//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfTime.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
    
        // I added this constructor so I could inject a db-connection into the context:
        public masterEntities(System.Data.Common.DbConnection dbConnection, bool contextOwnsConnection) 
            : base(dbConnection, contextOwnsConnection)
            {
        }
    
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<complain> complain { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<petition> petition { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
