//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int Id { get; set; }
        public Nullable<int> PetitionId { get; set; }
        public string Sender { get; set; }
        public string Message1 { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual petition petition { get; set; }
        public virtual user user { get; set; }
    }
}
