//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class petition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public petition()
        {
            this.message = new HashSet<message>();
        }
    
        public int Id { get; set; }
        public string Performer { get; set; }
        public string Requester { get; set; }
        public string Details { get; set; }
        public Nullable<int> HoursTransferred { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> message { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
